# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "test-unit"
  s.version = "2.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kouhei Sutou", "Haruka Yoshihara"]
  s.date = "2012-06-07"
  s.description = "Ruby 1.9.x bundles minitest not Test::Unit. Test::Unit\nbundled in Ruby 1.8.x had not been improved but unbundled\nTest::Unit (test-unit) is improved actively.\n"
  s.email = ["kou@cozmixng.org", "yoshihara@clear-code.com"]
  s.extra_rdoc_files = [
    "README.textile",
    "TODO"
  ]
  s.files = [
    "COPYING",
    "GPL",
    "PSFL",
    "README.textile",
    "Rakefile",
    "TODO",
    "lib/test-unit.rb",
    "lib/test/unit.rb",
    "lib/test/unit/assertionfailederror.rb",
    "lib/test/unit/assertions.rb",
    "lib/test/unit/attribute.rb",
    "lib/test/unit/autorunner.rb",
    "lib/test/unit/code-snippet-fetcher.rb",
    "lib/test/unit/collector.rb",
    "lib/test/unit/collector/descendant.rb",
    "lib/test/unit/collector/dir.rb",
    "lib/test/unit/collector/load.rb",
    "lib/test/unit/collector/objectspace.rb",
    "lib/test/unit/collector/xml.rb",
    "lib/test/unit/color-scheme.rb",
    "lib/test/unit/color.rb",
    "lib/test/unit/data.rb",
    "lib/test/unit/diff.rb",
    "lib/test/unit/error.rb",
    "lib/test/unit/exceptionhandler.rb",
    "lib/test/unit/failure.rb",
    "lib/test/unit/fixture.rb",
    "lib/test/unit/notification.rb",
    "lib/test/unit/omission.rb",
    "lib/test/unit/pending.rb",
    "lib/test/unit/priority.rb",
    "lib/test/unit/runner/console.rb",
    "lib/test/unit/runner/emacs.rb",
    "lib/test/unit/runner/xml.rb",
    "lib/test/unit/testcase.rb",
    "lib/test/unit/testresult.rb",
    "lib/test/unit/testsuite.rb",
    "lib/test/unit/testsuitecreator.rb",
    "lib/test/unit/ui/console/outputlevel.rb",
    "lib/test/unit/ui/console/testrunner.rb",
    "lib/test/unit/ui/emacs/testrunner.rb",
    "lib/test/unit/ui/testrunner.rb",
    "lib/test/unit/ui/testrunnermediator.rb",
    "lib/test/unit/ui/testrunnerutilities.rb",
    "lib/test/unit/ui/xml/testrunner.rb",
    "lib/test/unit/util/backtracefilter.rb",
    "lib/test/unit/util/method-owner-finder.rb",
    "lib/test/unit/util/observable.rb",
    "lib/test/unit/util/output.rb",
    "lib/test/unit/util/procwrapper.rb",
    "lib/test/unit/version.rb",
    "sample/adder.rb",
    "sample/subtracter.rb",
    "sample/test_adder.rb",
    "sample/test_subtracter.rb",
    "sample/test_user.rb",
    "test/collector/test-descendant.rb",
    "test/collector/test-load.rb",
    "test/collector/test_dir.rb",
    "test/collector/test_objectspace.rb",
    "test/fixtures/plus.csv",
    "test/run-test.rb",
    "test/test-assertions.rb",
    "test/test-attribute.rb",
    "test/test-code-snippet.rb",
    "test/test-color-scheme.rb",
    "test/test-color.rb",
    "test/test-data.rb",
    "test/test-diff.rb",
    "test/test-emacs-runner.rb",
    "test/test-fixture.rb",
    "test/test-notification.rb",
    "test/test-omission.rb",
    "test/test-pending.rb",
    "test/test-priority.rb",
    "test/test-testcase.rb",
    "test/test_error.rb",
    "test/test_failure.rb",
    "test/test_testresult.rb",
    "test/test_testsuite.rb",
    "test/testunit-test-util.rb",
    "test/ui/test_testrunmediator.rb",
    "test/util/test-method-owner-finder.rb",
    "test/util/test-output.rb",
    "test/util/test_backtracefilter.rb",
    "test/util/test_observable.rb",
    "test/util/test_procwrapper.rb"
  ]
  s.homepage = "http://test-unit.rubyforge.org/"
  s.licenses = ["Ruby's and PSFL (lib/test/unit/diff.rb)"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "test-unit"
  s.rubygems_version = "1.8.24"
  s.summary = "test-unit - Improved version of Test::Unit bundled in Ruby 1.8.x."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

